const address = [
    {label: 'ABC-高级生物技术中心', address: '意大利', value: 'ABC'},
    {label: 'ATCC-美国典型培养物保藏中心', address: '美国', value: 'ATCC'},
    {label: 'BCCM-比利时微生物协调保藏中心', address: '比利时', value: 'BCCM'},
    {label: 'BEA-西班牙海藻数据', address: '西班牙', value: 'BEA'},
    {label: 'CBA-澳大利亚玛丽•费尔法克斯女士细胞银行', address: '西班牙', value: '澳大利亚'},
    {label: 'CBS-真菌菌种保藏中心', address: '荷兰', value: 'CBS'},
    {label: 'CCAP-藻类和原生动物保藏中心', address: '英国', value: 'CCAP'},
    {label: 'CChRGM-智利微生物遗传资源中心', address: '智利', value: 'CChRGM'},
    {label: 'CCM-捷克微生物保藏中心', address: '捷克', value: 'CCM'},
    {label: 'CCTCC-中国典型培养物中心', address: '中国湖北省武汉市武汉大学', value: 'CCTCC'},
    {label: 'CCY-酵母菌保藏中心', address: '斯洛伐克', value: 'CCY'},
    {label: 'CECT-西班牙典型培养物保藏中心', value: 'CECT', address: '西班牙'},
    {label: 'CGMCC-中国微生物菌种保藏管理委员会普通微生物中心', value: 'CGMCC', address: '北京市朝阳区北辰西路1号院3号 中国科学院微生物研究所'},
    {label: 'CM-CNRG-MEXICO单位', value: 'CM-CNRG', address: 'MEXICO'},
    {label: 'CNCM-国家微生物保藏中心', value: 'CNCM', address: '法国'},
    {label: 'DBVPG-工业酵母菌保藏中心', value: 'DBVPG', address: '意大利'},
    {label: 'DSMZ-德国微生物保藏中心', value: 'DSMZ', address: '德国'},
    {label: 'ECACC-欧洲动物细胞保藏中心', value: 'ECACC', address: '英国'},
    {label: 'GDMCC-广东省微生物菌种保藏中心', value: 'GDMCC', address: '广东省微生物菌种保藏中心'},
    {label: 'IAFB-IAFB工业微生物保藏中心', value: 'IAFB', address: '波兰'},
    {label: 'IDAC-加拿大国际保藏中心', value: 'IDAC', address: '加拿大'},
    {label: 'IMI-国际真菌学研究所', value: 'IMI', address: '英国'},
    {label: 'IPOD,NITE-国家高级工业科学技术学院，国际专利生物保藏中心', value: 'IPOD,NITE', address: '日本'},
    {label: 'IZSLER-Isituto Zooprofilattico Sperimentale della Lombardia', value: 'IPOD,NITE', address: '意大利'},
    {label: 'KACC-韩国农业文化保藏中心', value: 'KACC', address: '韩国'},
    {label: 'KCCM-韩国微生物保藏中心', value: 'KCCM', address: '韩国'},
    {label: 'KCLRF-韩国细胞系研究基金会', value: 'KCLRF', address: '韩国'},
    {label: 'KCTC-韩国典型培养物保藏中心', value: 'KCTC', address: '韩国'},
    {label: 'MCC-微生物保藏中心', value: 'MCC', address: '美国'},
    {label: 'MSCL-拉脱维亚微生物菌种保藏中心', value: 'MSCL', address: '拉脱维亚'},
    {label: 'MTCC-微生物典型培养物保藏和基因银行', value: 'MTCC', address: '印度'},
    {label: 'NBIMCC-国家工业微生物和细胞保藏中心', value: 'NBIMCC', address: '保加利亚'},
    {label: 'NCAIM-国家农业和工业微生物保藏中心', value: 'NCAIM', address: '匈牙利'},
    {label: 'NCIMB-国家工业、食品和和海洋微生物保藏有限公司', value: 'NCIMB', address: '英国'},
    {label: 'NCMA-Provasoli-Guillard国家海洋藻类和微生物保藏中心', value: 'NRRL', address: '美国'},
    {label: 'NCTC-国家典型培养物保藏中心', value: 'NCTC', address: '英国'},
    {label: 'NCYC-国家酵母菌保藏中心', value: 'NCYC', address: '英国'},
    {label: 'NIBSC-国家生物标准和控制学会', value: 'NIBSC', address: '英国'},
    {label: 'NMI-国家度量学会', value: 'NMI', address: '澳大利亚'},
    {label: 'NPMD-国家技术评估学会，专利微生物保藏中心', value: 'NPMD', address: '日本'},
    {label: 'NRCA-国家抗生素研究中心', value: 'NRCA', address: '俄罗斯'},
    {label: 'NRRL-农业研究机构培养物保藏中心', value: 'NRRL', address: '美国'},
    {label: 'PCM-波兰微生物保藏中心', value: 'PCM', address: '波兰'},
    {label: 'VKM-俄罗斯微生物保藏中心', value: 'VKM', address: '俄罗斯'},
    {label: 'VKPM-俄罗斯国家工业微生物保藏中心', value: 'VKPM', address: '俄罗斯'},
    {label: 'VTTCC-VTT保藏中心', value: 'VTTCC', address: '芬兰'},
];

export default address
